### ISSUE TITLE
Possible item deletion due to PSI and TrashSlot

### ISSUE THREAD

**Issue by Chaogomu** [BBoldt/ThePioneers#35] opened 2016-03-07 16:40 UTC
The PSI spell table uses Delete to clear parts from the spell table, TrashSlot uses Delete to automatically send the item that the mouse is hovering over to the trash.

There are times where working in the spell table will move items from the player inventory to the trash slot. This can result in item deletion.

It seems more common when the player is experiencing lag.

**Comment by unascribed** [comment] 2016-04-23 21:41
Seems to be fixed in R6, I did Psi progression the other day and didn't lose any items. It happened pretty consistently in R5.

**Comment by SoullessWaffle** [comment] 2016-04-25 14:55
Oh, I was wondering where my Thaumonomicon went.
@unascribed where can I get R6? Do I build it myself?

**Comment by unascribed** [comment] 2016-04-25 16:17
R6 was the latest version when I posted that, now R7 is the latest version, and it is available on CurseForge already. If you're using the Curse Launcher then you already have it.

**Comment by SoullessWaffle** [comment] 2016-04-25 19:33
Oh, okay. I thought R6 was referring to an updated version of Psi or Trashslot.

I've been playing on R6 of The Pioneers for about a week now, and I've lost several items while working with Psi, including a Thaumonomicon, an (iron) CAD, and my Tinker's Construct pickaxe.
I don't know if this issue is the cause, but I suspect so.
I just updated to R7 and I'm curious to see if the issue has been fixed.

**Comment by Chaogomu** [comment] 2016-04-26 15:00
R7 still has the conflict.

Trashslot uses delete to remove item at cursor and shift delete to remove all of he same items. 

PSI uses delete and ctrl-shift-delete to clear the spell table

You can disable trashslot client side,doing sowill not prevent you from connecting to a server that has the mod running.

**Closed** 2024-09-23 07:32 UTC
Labels: Report Sent, Awaiting Fix, 1.8.9
