### ISSUE TITLE
Taking screenshots crashes the game

### ISSUE THREAD

**Issue by SoullessWaffle** [BBoldt/ThePioneers#70] opened 2016-05-01 11:26 UTC
To reproduce:

1. Press F2
2. Observe crash

This is the error report I get when I have my inventory open when taking the screenshot: http://pastebin.com/0HZJXrrt
And this is the one I get without having my inventory open: http://pastebin.com/12Xn7CWL

I should mention that I do have a couple of other mods added to the pack, so if no one can reproduce it in the base pack then it's probably one of them:

- [`StevesFactoryManager-A94.jar`](https://github.com/Vswe/ModJam3/pull/95)
- `AuraCascade-592.jar` (unreleased build to [fix Projectile Pumps](https://github.com/williewillus/Aura-Cascade/pull/12))
- [`liteloader-1.8.9-SNAPSHOT-release.jar`](http://jenkins.liteloader.com/view/1.8.9/job/LiteLoaderInstaller%201.8.9/)
- [`presencefootsteps-u8e.litemod`](https://github.com/Sollace/Presence-Footsteps)
- [`matmos-r29ub6_1.8.9.litemod`](https://github.com/Sollace/MAtmos)
- [`EnderCore-1.8.9-0.3.0.13-beta.jar`](http://ci.tterrag.com/job/EnderCore-1.8/)
- [`EnderIO-1.8.9-3.0.0.24_alpha.jar`](http://ci.tterrag.com/job/EnderIO-1.8/)

**Comment by williewillus** [comment] 2016-05-01 14:58
One of those mods is a deobf build

**Comment by SoullessWaffle** [comment] 2016-05-01 15:06
@williewillus Sorry, what would that mean? I'm guessing it's bad to have dev builds in your regular minecraft?

**Comment by williewillus** [comment] 2016-05-01 15:08
I mean one of those is a deobfuscated jar, and won't work in a regular mc environment, only in a dev environment

**Comment by SoullessWaffle** [comment] 2016-05-01 15:42
Do you mean one of the mods I listed in the post? If so that's strange, because I've used all of them and they all seem to be working.

**Comment by BBoldt** [comment] 2016-05-04 22:42
It looks like the error may be something relating with Sponge.

Might be something to do with Archimedes Ships+ though, as it uses some sponge stuff.

That being said, I have took numerous screenshots of my own with F2 and gotten no crashes so it's definitely one of the tweaks you've made to the pack causing it.

@darkevilmac does this look like something you've seen before?

Anyways, closing this issue because I can't reproduce it myself.

**Closed by BBoldt** 2016-05-04 22:42 UTC

**Comment by darkevilmac** [comment] 2016-05-04 22:47
Looks to be related to LiteLoader, MovingWorld doesn't Mixin to any stuff
related to screenshots. Try updating LiteLoader if there's an update
available. If not make a report to them.

**Comment by BBoldt** [comment] 2016-05-04 22:55
Also, I should add, if you're going to add your own mods, please try to reproduce it without the added mods before reporting.
